import * as stylex from "@stylexjs/stylex";
import { breakpoints, colors, fonts } from "@/styles/tokens.stylex";

export const styles = stylex.create({
  zone: {
    scrollMarginTop: {
      default: "10vh",
      [breakpoints.compact]: "16vh",
    },
  },
  stratumDrop: (dropVh: number) => ({
    paddingTop: `${dropVh}vh`,
  }),
  extendedZone: {
    minHeight: "152vh",
  },
  stratumTitle: {
    color: colors.ice,
    fontSize: {
      default: "clamp(3rem, 8vw, 7rem)",
      [breakpoints.compact]: "clamp(2rem, 10vw, 4.5rem)",
    },
    fontVariationSettings: {
      default: '"wdth" 125',
      [breakpoints.compact]: '"wdth" 112',
    },
    fontWeight: 760,
    letterSpacing: {
      default: "0.055em",
      [breakpoints.compact]: "0.035em",
    },
    lineHeight: 0.96,
    overflowWrap: {
      default: "normal",
      [breakpoints.compact]: "anywhere",
    },
    textTransform: "uppercase",
    maxWidth: "100%",
    scrollMarginTop: "100px",
  },
  stratumSubtitle: {
    color: "rgba(159, 195, 207, 0.9)",
    display: "block",
    fontFamily: fonts.mono,
    fontSize: {
      default: "0.68rem",
      [breakpoints.compact]: "0.59rem",
    },
    letterSpacing: {
      default: "0.3em",
      [breakpoints.compact]: "0.2em",
      [breakpoints.tiny]: "0.16em",
    },
    lineHeight: 1.65,
    textTransform: "uppercase",
    marginTop: "1rem",
    maxWidth: {
      default: null,
      [breakpoints.compact]: "34ch",
    },
  },
  entryTitle: {
    color: colors.iceBright,
    fontSize: {
      default: "clamp(1.7rem, 3.2vw, 2.9rem)",
      [breakpoints.compact]: "clamp(1.55rem, 8vw, 2.3rem)",
    },
    fontVariationSettings: '"wdth" 112',
    fontWeight: 620,
    letterSpacing: "-0.025em",
    lineHeight: 1.05,
    textWrap: "balance",
    marginTop: "1.4rem",
    maxWidth: "18ch",
  },
  entryCopy: {
    color: colors.bodyText,
    fontSize: {
      default: "1.02rem",
      [breakpoints.compact]: "0.95rem",
      [breakpoints.tiny]: "0.92rem",
    },
    lineHeight: 1.75,
    textWrap: "pretty",
    marginTop: "1.2rem",
  },
  tagList: {
    gap: "0.55rem",
    listStyle: "none",
    display: "flex",
    flexWrap: "wrap",
    marginTop: "1.6rem",
  },
  tag: {
    borderColor: "rgba(159, 195, 207, 0.3)",
    borderStyle: "solid",
    borderWidth: "1px",
    paddingBlock: "0.42rem",
    paddingInline: "0.62rem",
    color: colors.ice,
    fontFamily: fonts.mono,
    fontSize: "0.56rem",
    letterSpacing: "0.12em",
    textTransform: "uppercase",
  },
  context: {
    borderColor: "rgba(100, 240, 210, 0.23)",
    borderStyle: "solid",
    borderWidth: "1px",
    backgroundColor: "rgba(100, 240, 210, 0.045)",
    marginBottom: "-0.2rem",
    marginLeft: "-0.3rem",
    marginRight: "-0.3rem",
    marginTop: "2rem",
    paddingBottom: "1.45rem",
    paddingLeft: "1.4rem",
    paddingRight: "1.4rem",
    paddingTop: "1.35rem",
  },
  contextLabel: {
    color: colors.biolume,
    fontFamily: fonts.mono,
    fontSize: "0.56rem",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
  },
  contextTitle: {
    color: colors.iceBright,
    display: "block",
    fontSize: "0.9rem",
    fontWeight: 560,
    marginTop: "0.7rem",
  },
  contextCopy: {
    display: "block",
    marginTop: "0.6rem",
  },
  contextParagraph: {
    color: "rgba(201, 218, 225, 0.85)",
    fontSize: "0.88rem",
    lineHeight: 1.65,
  },
  contextParagraphFollowing: {
    marginTop: "0.65rem",
  },
  protocolList: {
    listStyle: "none",
    borderTopColor: "rgba(159, 195, 207, 0.28)",
    borderTopStyle: "solid",
    borderTopWidth: "1px",
    marginTop: "2.3rem",
  },
  protocolItem: {
    gap: {
      default: "1.2rem",
      [breakpoints.tiny]: "0.8rem",
    },
    paddingBlock: "1.35rem",
    paddingInline: "0",
    display: "grid",
    gridTemplateColumns: {
      default: "3rem minmax(12rem, 0.72fr) 1fr",
      [breakpoints.compact]: "2.5rem 1fr",
      [breakpoints.tiny]: "2rem minmax(0, 1fr)",
    },
    borderBottomColor: "rgba(159, 195, 207, 0.28)",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
  },
  itemSequence: {
    color: colors.biolume,
    fontFamily: fonts.mono,
    fontSize: "0.62rem",
  },
  protocolTitle: {
    color: colors.iceBright,
    fontSize: "0.94rem",
    fontWeight: 560,
  },
  protocolDescription: {
    gridColumn: {
      default: "auto",
      [breakpoints.compact]: "2",
    },
    color: "rgba(201, 218, 225, 0.82)",
    fontSize: "0.88rem",
    lineHeight: 1.6,
  },
  specimenGrid: {
    display: "grid",
    gridTemplateColumns: {
      default: "repeat(2, 1fr)",
      [breakpoints.compact]: "1fr",
    },
    borderLeftColor: "rgba(159, 195, 207, 0.28)",
    borderLeftStyle: "solid",
    borderLeftWidth: "1px",
    borderTopColor: "rgba(159, 195, 207, 0.28)",
    borderTopStyle: "solid",
    borderTopWidth: "1px",
    marginTop: "2.4rem",
  },
  specimen: {
    padding: {
      default: "1.35rem",
      [breakpoints.tiny]: "1.1rem",
    },
    borderBottomColor: "rgba(159, 195, 207, 0.28)",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    borderRightColor: "rgba(159, 195, 207, 0.28)",
    borderRightStyle: "solid",
    borderRightWidth: "1px",
    minHeight: {
      default: "220px",
      [breakpoints.compact]: "205px",
    },
  },
  specimenTitle: {
    color: colors.iceBright,
    fontSize: "1.55rem",
    fontVariationSettings: '"wdth" 112',
    fontWeight: 600,
    marginTop: "2rem",
  },
  specimenSignal: {
    color: colors.biolume,
    display: "block",
    fontFamily: fonts.mono,
    fontSize: "0.62rem",
    fontWeight: 500,
    letterSpacing: "0.06em",
    overflowWrap: "anywhere",
    textTransform: "uppercase",
    marginTop: "0.7rem",
  },
  specimenDescription: {
    color: "rgba(201, 218, 225, 0.78)",
    fontSize: "0.84rem",
    lineHeight: 1.6,
    marginTop: "0.85rem",
  },
});
