import * as stylex from "@stylexjs/stylex";
import { breakpoints, colors, fonts, motion } from "@/styles/tokens.stylex";
import { echoMapMotion } from "./motion.stylex";

const radarSweep = stylex.keyframes({
  "0%": { opacity: 0.56, transform: "rotate(var(--echo-radar-sweep-start))" },
  "24%": { opacity: 0.82 },
  "57%": { opacity: 0.64 },
  "81%": { opacity: 0.9 },
  "100%": {
    opacity: 0.56,
    transform: "rotate(calc(var(--echo-radar-sweep-start) + 360deg))",
  },
});

const searchPulse = stylex.keyframes({
  "0%": { opacity: 0, transform: "translate(-50%, -50%) scale(0.1)" },
  "9%": { opacity: 0.58 },
  "74%, 100%": { opacity: 0, transform: "translate(-50%, -50%) scale(1)" },
});

const fieldShimmer = stylex.keyframes({
  "0%, 100%": { opacity: 0.62 },
  "31%": { opacity: 0.9 },
  "66%": { opacity: 0.7 },
  "82%": { opacity: 1 },
});

const contactBreathing = stylex.keyframes({
  "0%, 100%": { opacity: 0.48, scale: "0.84" },
  "27%": { opacity: 0.78, scale: "1.02" },
  "58%": { opacity: 0.61, scale: "0.92" },
  "79%": { opacity: 0.94, scale: "1.08" },
});

const contactAuraBreathing = stylex.keyframes({
  "0%, 100%": { opacity: 0.16, scale: "0.72" },
  "34%": { opacity: 0.38, scale: "1.04" },
  "68%": { opacity: 0.22, scale: "0.88" },
});

const contactDrift = stylex.keyframes({
  "0%, 100%": { transform: "translate3d(0, 0, 0)" },
  "32%": {
    transform: "translate3d(var(--echo-contact-drift-x-1), var(--echo-contact-drift-y-1), 0)",
  },
  "69%": {
    transform: "translate3d(var(--echo-contact-drift-x-2), var(--echo-contact-drift-y-2), 0)",
  },
});

const contactSweepAnswer = stylex.keyframes({
  "0%": { opacity: 0, scale: "0.62" },
  "1.5%": { opacity: 0.8, scale: "1" },
  "4.5%": { opacity: 0.22, scale: "1.42" },
  "7.5%, 100%": { opacity: 0, scale: "1.58" },
});

const lockBreathing = stylex.keyframes({
  "0%, 100%": { opacity: 0.74, scale: "0.96" },
  "46%": { opacity: 1, scale: "1.03" },
  "73%": { opacity: 0.82, scale: "0.99" },
});

const statusBlink = stylex.keyframes({
  "0%, 100%": { opacity: 0.42, scale: "0.82" },
  "38%": { opacity: 1, scale: "1.08" },
  "67%": { opacity: 0.68, scale: "0.94" },
});

const openingCueBreath = stylex.keyframes({
  "0%, 100%": { opacity: 0.58, scale: "0.9" },
  "48%": { opacity: 1, scale: "1.06" },
  "76%": { opacity: 0.74, scale: "0.98" },
});

const openingCueProgress = stylex.keyframes({
  "0%": { opacity: 0.28, transform: "scaleX(0.04)" },
  "64%": { opacity: 0.62 },
  "100%": { opacity: 0.82, transform: "scaleX(1)" },
});

const panelArrival = stylex.keyframes({
  "0%": { opacity: 0, transform: "translate3d(0, 0.6rem, 0)" },
  "66%": { opacity: 0.88 },
  "100%": { opacity: 1, transform: "none" },
});

export const styles = stylex.create({
  dialog: {
    inset: 0,
    margin: 0,
    padding: 0,
    borderWidth: 0,
    overflow: "hidden",
    backgroundColor: "rgba(0, 4, 9, 0)",
    color: colors.bodyText,
    transitionDuration: echoMapMotion.closeDuration,
    transitionProperty: "background-color",
    transitionTimingFunction: motion.easeOut,
    height: {
      default: "100vh",
      "@supports (height: 100dvh)": "100dvh",
    },
    maxHeight: "none",
    maxWidth: "none",
    width: "100vw",
    "::backdrop": {
      backgroundColor: "transparent",
    },
  },
  dialogExpanded: {
    backgroundColor: "rgba(0, 4, 9, 0.82)",
  },
  stage: {
    padding: {
      default: "clamp(0.7rem, 2vw, 1.4rem)",
      [breakpoints.compact]: "0.45rem",
    },
    placeItems: "center",
    display: "grid",
    position: "relative",
    height: "100%",
    width: "100%",
  },
  backdropButton: {
    inset: 0,
    padding: 0,
    borderWidth: 0,
    backgroundColor: "transparent",
    cursor: "default",
    position: "absolute",
  },
  console: {
    borderColor: "rgba(159, 195, 207, 0.42)",
    borderRadius: 54,
    borderStyle: "solid",
    borderWidth: 1,
    overflow: "hidden",
    backgroundColor: "rgba(1, 9, 16, 0.975)",
    backgroundImage:
      "radial-gradient(circle at 13% 7%, rgba(100, 240, 210, 0.09), transparent 28%), radial-gradient(circle at 82% 92%, rgba(70, 121, 154, 0.11), transparent 34%), linear-gradient(rgba(100, 240, 210, 0.026) 1px, transparent 1px), linear-gradient(90deg, rgba(100, 240, 210, 0.026) 1px, transparent 1px)",
    backgroundSize: "auto, auto, 52px 52px, 52px 52px",
    boxShadow: "0 34px 110px rgba(0, 0, 0, 0.62), inset 0 1px 0 rgba(230, 241, 244, 0.08)",
    display: "grid",
    gridTemplateRows: "auto minmax(0, 1fr)",
    opacity: 0.24,
    pointerEvents: "auto",
    position: "relative",
    transform:
      "translate3d(var(--echo-map-translate-x), var(--echo-map-translate-y), 0) scale(var(--echo-map-scale-x), var(--echo-map-scale-y))",
    transformOrigin: "50% 50%",
    transitionDuration: echoMapMotion.openDuration,
    transitionProperty: "transform, opacity, border-radius, box-shadow",
    transitionTimingFunction: "cubic-bezier(0.16, 1, 0.3, 1)",
    willChange: "transform, opacity",
    zIndex: 1,
    height: "min(49rem, 100%)",
    maxWidth: 1180,
    width: "100%",
  },
  consoleExpanded: {
    borderRadius: {
      default: 30,
      [breakpoints.compact]: 22,
    },
    opacity: 1,
    transform: "translate3d(0, 0, 0) scale(1, 1)",
  },
  consoleClosing: {
    borderRadius: 54,
    pointerEvents: "none",
    transitionDuration: echoMapMotion.closeDuration,
    transitionTimingFunction: "cubic-bezier(0.55, 0, 0.84, 0.24)",
  },
  consoleHeader: {
    gap: "1rem",
    paddingBlock: {
      default: "1rem",
      [breakpoints.compact]: "0.72rem",
    },
    paddingInline: {
      default: "clamp(1.15rem, 2.4vw, 2rem)",
      [breakpoints.compact]: "0.85rem",
    },
    alignItems: "center",
    display: "flex",
    justifyContent: "space-between",
    borderBottomColor: "rgba(159, 195, 207, 0.18)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    minHeight: {
      default: 90,
      [breakpoints.compact]: 76,
    },
  },
  identity: {
    gap: {
      default: "0.9rem",
      [breakpoints.compact]: "0.65rem",
    },
    alignItems: "center",
    display: "flex",
    minWidth: 0,
  },
  titleGroup: {
    minWidth: 0,
  },
  vehicleMark: {
    overflow: "hidden",
    flexBasis: "auto",
    flexGrow: 0,
    flexShrink: 0,
    position: "relative",
    height: {
      default: 58,
      [breakpoints.compact]: 48,
    },
    width: {
      default: 44,
      [breakpoints.compact]: 36,
    },
  },
  eyebrow: {
    overflow: "hidden",
    color: colors.biolume,
    fontFamily: fonts.mono,
    fontSize: {
      default: "0.54rem",
      [breakpoints.compact]: "0.47rem",
    },
    letterSpacing: {
      default: "0.18em",
      [breakpoints.compact]: "0.1em",
    },
    textOverflow: "ellipsis",
    textTransform: "uppercase",
    whiteSpace: "nowrap",
  },
  heading: {
    color: colors.iceBright,
    fontSize: {
      default: "clamp(1.75rem, 3vw, 2.8rem)",
      [breakpoints.compact]: "1.45rem",
    },
    fontVariationSettings: '"wdth" 108',
    fontWeight: 680,
    letterSpacing: "0.025em",
    lineHeight: 0.96,
    textTransform: "uppercase",
    marginTop: "0.28rem",
  },
  closeButton: {
    padding: 0,
    borderColor: {
      default: "rgba(159, 195, 207, 0.34)",
      ":hover": "rgba(100, 240, 210, 0.78)",
    },
    borderRadius: 999,
    borderStyle: "solid",
    borderWidth: 1,
    placeItems: "center",
    backgroundColor: {
      default: "rgba(1, 9, 14, 0.54)",
      ":hover": "rgba(100, 240, 210, 0.09)",
    },
    color: {
      default: colors.ice,
      ":hover": colors.biolume,
    },
    cursor: "pointer",
    display: "grid",
    flexBasis: "auto",
    flexGrow: 0,
    flexShrink: 0,
    fontFamily: fonts.mono,
    fontSize: "1.45rem",
    fontWeight: 300,
    lineHeight: 1,
    scale: {
      default: "1",
      ":hover": "1.04",
      ":active": "0.94",
    },
    transitionDuration: "220ms",
    transitionProperty: "background-color, border-color, color, scale",
    transitionTimingFunction: motion.easeOut,
    height: 44,
    minHeight: 44,
    minWidth: 44,
    width: 44,
  },
  openingCue: {
    gap: "0.65rem",
    padding: "clamp(1rem, 3vw, 2.5rem)",
    alignContent: "center",
    display: "grid",
    justifyItems: "center",
    gridColumn: "1",
    gridRow: "2",
    opacity: 0,
    pointerEvents: "none",
    transform: "translate3d(0, 0.35rem, 0)",
    transitionDuration: {
      default: "200ms",
      [breakpoints.reducedMotion]: "0ms",
    },
    transitionProperty: "opacity, transform",
    transitionTimingFunction: motion.easeOut,
    zIndex: 1,
    minHeight: 0,
  },
  openingCueActive: {
    opacity: 1,
    transform: "translate3d(0, 0, 0)",
  },
  openingCueSignal: {
    borderColor: "rgba(100, 240, 210, 0.38)",
    borderRadius: "50%",
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow: "0 0 24px rgba(100, 240, 210, 0.08)",
    display: "block",
    position: "relative",
    height: 38,
    width: 38,
  },
  openingCueSignalActive: {
    animationDuration: "1.05s",
    animationIterationCount: "infinite",
    animationName: {
      default: openingCueBreath,
      [breakpoints.reducedMotion]: "none",
    },
    animationTimingFunction: "ease-in-out",
  },
  openingCueSignalCore: {
    borderRadius: "50%",
    backgroundColor: colors.biolume,
    boxShadow: "0 0 12px rgba(100, 240, 210, 0.68)",
    display: "block",
    position: "absolute",
    transform: "translate(-50%, -50%)",
    height: 5,
    left: "50%",
    top: "50%",
    width: 5,
  },
  openingCueLabel: {
    color: "rgba(201, 218, 225, 0.72)",
    fontFamily: fonts.mono,
    fontSize: {
      default: "0.52rem",
      [breakpoints.compact]: "0.48rem",
    },
    letterSpacing: "0.15em",
    lineHeight: 1.5,
    textAlign: "center",
    textTransform: "uppercase",
  },
  openingCueTrack: {
    overflow: "hidden",
    backgroundColor: "rgba(159, 195, 207, 0.13)",
    display: "block",
    height: 1,
    width: "min(11rem, 46vw)",
  },
  openingCueProgress: {
    backgroundImage: "linear-gradient(90deg, rgba(100, 240, 210, 0.18), rgba(100, 240, 210, 0.92))",
    display: "block",
    opacity: 0.28,
    transform: "scaleX(0.04)",
    transformOrigin: "0 50%",
    height: "100%",
    width: "100%",
  },
  openingCueProgressActive: {
    animationDuration: echoMapMotion.openDuration,
    animationFillMode: "both",
    animationName: {
      default: openingCueProgress,
      [breakpoints.reducedMotion]: "none",
    },
    animationTimingFunction: "cubic-bezier(0.16, 1, 0.3, 1)",
  },
  consoleBody: {
    padding: {
      default: "clamp(1rem, 2.4vw, 2rem)",
      [breakpoints.compact]: "0.8rem",
    },
    gap: {
      default: "clamp(1.3rem, 3vw, 2.8rem)",
      [breakpoints.compact]: "1rem",
    },
    overflow: {
      default: "hidden",
      [breakpoints.compact]: "auto",
    },
    alignContent: {
      default: "stretch",
      [breakpoints.compact]: "start",
    },
    display: "grid",
    gridColumn: "1",
    gridRow: "2",
    gridAutoRows: {
      default: "minmax(0, 1fr)",
      [breakpoints.compact]: "max-content",
    },
    gridTemplateColumns: {
      default: "minmax(18rem, 1.05fr) minmax(20rem, 0.95fr)",
      [breakpoints.mediumOnly]: "minmax(16rem, 0.92fr) minmax(18rem, 1.08fr)",
      [breakpoints.compact]: "1fr",
    },
    opacity: 1,
    transitionDuration: {
      default: "220ms",
      [breakpoints.reducedMotion]: "0ms",
    },
    transitionProperty: "opacity",
    transitionTimingFunction: motion.easeOut,
    visibility: "visible",
    minHeight: 0,
  },
  consoleBodyDormant: {
    opacity: 0,
    pointerEvents: "none",
    visibility: "hidden",
  },
  radarPanel: {
    gap: "0.85rem",
    alignContent: "start",
    alignSelf: {
      default: "stretch",
      [breakpoints.compact]: "start",
    },
    display: "grid",
    overflowY: {
      default: "auto",
      [breakpoints.compact]: "visible",
    },
    overscrollBehaviorY: "contain",
    minHeight: {
      default: 0,
      [breakpoints.compact]: "max-content",
    },
  },
  radarPanelArrived: {
    animationDelay: "15ms",
    animationDuration: "300ms",
    animationFillMode: "both",
    animationName: {
      default: panelArrival,
      [breakpoints.reducedMotion]: "none",
    },
    animationTimingFunction: motion.easeOut,
  },
  radarContent: {
    gap: "0.85rem",
    overflow: "visible",
    display: "grid",
    gridAutoRows: "max-content",
    minHeight: "max-content",
  },
  panelHeader: {
    gap: "1rem",
    alignItems: "start",
    display: "flex",
    justifyContent: "space-between",
  },
  panelLabel: {
    color: colors.ice,
    fontFamily: fonts.mono,
    fontSize: "0.52rem",
    letterSpacing: "0.16em",
    lineHeight: 1.5,
    textTransform: "uppercase",
  },
  liveStatus: {
    gap: "0.42rem",
    alignItems: "center",
    color: "rgba(100, 240, 210, 0.76)",
    display: {
      default: "inline-flex",
      [breakpoints.compact]: "none",
    },
    fontFamily: fonts.mono,
    fontSize: "0.48rem",
    letterSpacing: "0.1em",
    textTransform: "uppercase",
  },
  liveDot: {
    borderRadius: "50%",
    animationDuration: "5.2s",
    animationIterationCount: "infinite",
    animationName: {
      default: statusBlink,
      [breakpoints.reducedMotion]: "none",
    },
    backgroundColor: colors.biolume,
    boxShadow: "0 0 8px rgba(100, 240, 210, 0.62)",
    height: 6,
    width: 6,
  },
  description: {
    color: "rgba(201, 218, 225, 0.67)",
    fontSize: {
      default: "0.79rem",
      [breakpoints.compact]: "0.73rem",
    },
    lineHeight: 1.55,
    maxWidth: "54ch",
  },
  radarZoneMeta: {
    gap: "0.8rem",
    alignItems: "baseline",
    display: "flex",
    justifyContent: "space-between",
    minWidth: 0,
  },
  radarZoneName: {
    overflow: "hidden",
    color: colors.iceBright,
    fontSize: "0.74rem",
    fontWeight: 600,
    letterSpacing: "0.04em",
    textOverflow: "ellipsis",
    textTransform: "uppercase",
    whiteSpace: "nowrap",
  },
  radarZoneRange: {
    color: "rgba(100, 240, 210, 0.72)",
    flexShrink: 0,
    fontFamily: fonts.mono,
    fontSize: "0.47rem",
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    whiteSpace: "nowrap",
  },
  radarField: {
    margin: 0,
    borderColor: "rgba(100, 240, 210, 0.25)",
    borderRadius: "50%",
    borderStyle: "solid",
    borderWidth: 1,
    overflow: "hidden",
    aspectRatio: "1",
    backgroundColor: "rgba(0, 15, 22, 0.64)",
    backgroundImage:
      "radial-gradient(circle, rgba(100, 240, 210, 0.025) 0 2%, transparent 2.2%), radial-gradient(circle, transparent 24.5%, rgba(100, 240, 210, 0.12) 24.8%, transparent 25.2%, transparent 49.5%, rgba(100, 240, 210, 0.1) 49.8%, transparent 50.2%, transparent 74.5%, rgba(100, 240, 210, 0.08) 74.8%, transparent 75.2%), radial-gradient(circle at center, rgba(9, 66, 72, 0.22), rgba(0, 8, 15, 0.08) 68%)",
    boxShadow: "inset 0 0 44px rgba(0, 0, 0, 0.62), 0 0 40px rgba(100, 240, 210, 0.055)",
    justifySelf: "center",
    position: "relative",
    height: {
      default: "auto",
      [breakpoints.compact]: "min(76vw, 18rem)",
    },
    width: {
      default: "min(100%, 22rem)",
      [breakpoints.compact]: "min(76vw, 18rem)",
    },
  },
  radarAxes: {
    inset: "8%",
    borderRadius: "50%",
    backgroundImage:
      "linear-gradient(transparent 49.7%, rgba(100, 240, 210, 0.11) 50%, transparent 50.3%), linear-gradient(90deg, transparent 49.7%, rgba(100, 240, 210, 0.11) 50%, transparent 50.3%)",
    opacity: 0.72,
    pointerEvents: "none",
    position: "absolute",
  },
  radarAxesActive: {
    animationDuration: "var(--echo-radar-shimmer-duration)",
    animationIterationCount: "infinite",
    animationName: {
      default: fieldShimmer,
      [breakpoints.reducedMotion]: "none",
    },
    animationTimingFunction: "ease-in-out",
  },
  radarSweep: {
    inset: "2.5%",
    borderRadius: "50%",
    backgroundImage:
      "conic-gradient(from -61deg, transparent 0deg, rgba(100, 240, 210, 0.012) 18deg, rgba(100, 240, 210, 0.08) 44deg, rgba(100, 240, 210, 0.38) 61deg, transparent 66deg)",
    opacity: 0,
    pointerEvents: "none",
    position: "absolute",
    transform: "rotate(var(--echo-radar-sweep-start))",
    transformOrigin: "50% 50%",
  },
  radarSweepActive: {
    animationDuration: "var(--echo-radar-sweep-duration)",
    animationIterationCount: "infinite",
    animationName: {
      default: radarSweep,
      [breakpoints.reducedMotion]: "none",
    },
    animationTimingFunction: "linear",
    opacity: 1,
  },
  searchPulse: {
    borderColor: "rgba(100, 240, 210, 0.48)",
    borderRadius: "50%",
    borderStyle: "solid",
    borderWidth: 1,
    opacity: 0,
    pointerEvents: "none",
    position: "absolute",
    transform: "translate(-50%, -50%) scale(0.12)",
    height: "94%",
    left: "50%",
    top: "50%",
    width: "94%",
  },
  searchPulseActive: {
    animationDuration: "var(--echo-radar-search-duration)",
    animationIterationCount: "infinite",
    animationName: {
      default: searchPulse,
      [breakpoints.reducedMotion]: "none",
    },
    animationTimingFunction: "cubic-bezier(0.16, 1, 0.3, 1)",
  },
  searchPulseSecondary: {
    animationDelay: "-3.1s",
    opacity: 0,
  },
  contactList: {
    inset: 0,
    listStyle: "none",
    margin: 0,
    padding: 0,
    position: "absolute",
    zIndex: 2,
  },
  contactDriftFrame: {
    inset: 0,
    placeItems: "center",
    display: "grid",
    pointerEvents: "none",
    position: "absolute",
  },
  contactDrifting: {
    animationDelay: "var(--echo-contact-drift-delay)",
    animationDuration: "var(--echo-contact-drift-duration)",
    animationIterationCount: "infinite",
    animationName: {
      default: contactDrift,
      [breakpoints.reducedMotion]: "none",
    },
    animationTimingFunction: "ease-in-out",
  },
  contactTarget: {
    padding: 0,
    borderWidth: 0,
    borderRadius: "50%",
    outlineColor: {
      default: "transparent",
      ":focus-visible": colors.biolume,
    },
    outlineOffset: 4,
    outlineStyle: "solid",
    outlineWidth: 2,
    placeItems: "center",
    backgroundColor: "transparent",
    cursor: "pointer",
    display: "grid",
    position: "relative",
    transitionDuration: "220ms",
    transitionProperty: "background-color, outline-color",
    transitionTimingFunction: motion.easeOut,
    height: 44,
    width: 44,
  },
  contactTargetActive: {
    backgroundColor: "rgba(100, 240, 210, 0.055)",
  },
  contactTargetSelected: {
    backgroundColor: "rgba(100, 240, 210, 0.11)",
    outlineColor: "rgba(100, 240, 210, 0.58)",
  },
  contactAura: {
    borderColor: "rgba(100, 240, 210, 0.72)",
    borderRadius: "50%",
    borderStyle: "solid",
    borderWidth: 1,
    animationDelay: "var(--echo-contact-pulse-delay)",
    animationDuration: "var(--echo-contact-pulse-duration)",
    animationIterationCount: "infinite",
    animationName: {
      default: contactAuraBreathing,
      [breakpoints.reducedMotion]: "none",
    },
    animationTimingFunction: "cubic-bezier(0.42, 0, 0.24, 1)",
    opacity: 0.18,
    pointerEvents: "none",
    position: "absolute",
    height: "var(--echo-contact-aura-size)",
    width: "var(--echo-contact-aura-size)",
  },
  contactAuraActive: {
    borderColor: colors.biolume,
    opacity: 0.52,
  },
  contactSweepHit: {
    borderColor: "rgba(230, 241, 244, 0.78)",
    borderRadius: "50%",
    borderStyle: "solid",
    borderWidth: 1,
    opacity: 0,
    pointerEvents: "none",
    position: "absolute",
    height: "var(--echo-contact-aura-size)",
    width: "var(--echo-contact-aura-size)",
  },
  contactSweepHitActive: {
    animationDelay: "var(--echo-contact-hit-delay)",
    animationDuration: "var(--echo-radar-sweep-duration)",
    animationIterationCount: "infinite",
    animationName: {
      default: contactSweepAnswer,
      [breakpoints.reducedMotion]: "none",
    },
    animationTimingFunction: "linear",
  },
  contactDot: {
    borderColor: "rgba(100, 240, 210, 0.82)",
    borderRadius: "50%",
    borderStyle: "solid",
    borderWidth: 1,
    animationDelay: "var(--echo-contact-pulse-delay)",
    animationDuration: "var(--echo-contact-pulse-duration)",
    animationIterationCount: "infinite",
    animationName: {
      default: contactBreathing,
      [breakpoints.reducedMotion]: "none",
    },
    animationTimingFunction: "cubic-bezier(0.42, 0, 0.24, 1)",
    backgroundColor: "rgba(100, 240, 210, 0.34)",
    boxShadow: "0 0 8px rgba(100, 240, 210, 0.42)",
    opacity: 0.62,
    pointerEvents: "none",
    position: "absolute",
    height: "var(--echo-contact-size)",
    width: "var(--echo-contact-size)",
  },
  contactDotActive: {
    backgroundColor: colors.biolume,
    boxShadow: "0 0 5px rgba(230, 241, 244, 0.8), 0 0 20px rgba(100, 240, 210, 0.9)",
    opacity: 1,
  },
  contactLabel: {
    color: colors.biolume,
    fontFamily: fonts.mono,
    fontSize: "0.42rem",
    letterSpacing: "0.08em",
    opacity: 0,
    pointerEvents: "none",
    position: "absolute",
    textShadow: "0 0 10px rgba(100, 240, 210, 0.8)",
    textTransform: "uppercase",
    transform: "translate(-50%, 1rem)",
    transitionDuration: "260ms",
    transitionProperty: "opacity, transform",
    transitionTimingFunction: motion.easeOut,
    whiteSpace: "nowrap",
    left: "50%",
    top: "50%",
  },
  contactLabelActive: {
    opacity: {
      default: 0.92,
      [breakpoints.compact]: 0,
    },
    transform: "translate(-50%, 1.2rem)",
  },
  centerLock: {
    borderColor: "rgba(100, 240, 210, 0.46)",
    borderRadius: "50%",
    borderStyle: "solid",
    borderWidth: 1,
    placeItems: "center",
    backgroundColor: "rgba(1, 9, 16, 0.86)",
    display: "grid",
    pointerEvents: "none",
    position: "absolute",
    transform: "translate(-50%, -50%)",
    height: {
      default: 72,
      [breakpoints.compact]: 58,
    },
    left: "50%",
    top: "50%",
    width: {
      default: 72,
      [breakpoints.compact]: 58,
    },
    zIndex: 3,
  },
  centerLockActive: {
    animationDuration: "5.6s",
    animationIterationCount: "infinite",
    animationName: {
      default: lockBreathing,
      [breakpoints.reducedMotion]: "none",
    },
    animationTimingFunction: "ease-in-out",
  },
  centerDepth: {
    color: colors.iceBright,
    fontFamily: fonts.mono,
    fontSize: {
      default: "0.58rem",
      [breakpoints.compact]: "0.48rem",
    },
    letterSpacing: "0.08em",
    textAlign: "center",
    textShadow: "0 0 12px rgba(100, 240, 210, 0.45)",
    textTransform: "uppercase",
  },
  radarReadout: {
    borderColor: "rgba(159, 195, 207, 0.18)",
    borderRadius: 14,
    borderStyle: "solid",
    borderWidth: 1,
    gap: "0.48rem",
    paddingBlock: "0.72rem",
    paddingInline: "0.8rem",
    backgroundColor: "rgba(2, 15, 22, 0.72)",
    display: "grid",
    marginTop: {
      default: 0,
      [breakpoints.compact]: "1rem",
    },
    minWidth: 0,
  },
  contactReadoutHeader: {
    gap: "0.8rem",
    alignItems: "baseline",
    display: "flex",
    justifyContent: "space-between",
    minWidth: 0,
  },
  contactKind: {
    color: colors.biolume,
    fontFamily: fonts.mono,
    fontSize: "0.46rem",
    letterSpacing: "0.11em",
    textTransform: "uppercase",
  },
  contactIdentity: {
    gap: "0.4rem",
    alignItems: "baseline",
    display: "flex",
    flexWrap: "wrap",
    minWidth: 0,
  },
  contactName: {
    color: colors.iceBright,
    fontSize: {
      default: "0.76rem",
      [breakpoints.compact]: "0.7rem",
    },
    fontWeight: 600,
    lineHeight: 1.35,
  },
  contactScientificName: {
    color: "rgba(159, 195, 207, 0.74)",
    fontFamily: fonts.mono,
    fontSize: "0.51rem",
    fontStyle: "italic",
  },
  contactDescription: {
    color: "rgba(201, 218, 225, 0.76)",
    fontSize: {
      default: "0.68rem",
      [breakpoints.compact]: "0.65rem",
    },
    lineHeight: 1.48,
  },
  contactMeta: {
    gap: "0.35rem 0.9rem",
    color: "rgba(159, 195, 207, 0.66)",
    display: "flex",
    flexWrap: "wrap",
    fontFamily: fonts.mono,
    fontSize: "0.44rem",
    letterSpacing: "0.035em",
    lineHeight: 1.45,
    textTransform: "uppercase",
  },
  contactNote: {
    borderLeftColor: "rgba(100, 240, 210, 0.34)",
    borderLeftStyle: "solid",
    borderLeftWidth: 1,
    paddingLeft: "0.55rem",
    color: "rgba(159, 195, 207, 0.58)",
    fontSize: "0.58rem",
    lineHeight: 1.45,
  },
  contactVector: {
    color: "rgba(159, 195, 207, 0.72)",
    fontFamily: fonts.mono,
    fontSize: "0.48rem",
    letterSpacing: "0.06em",
    textAlign: "right",
    whiteSpace: "nowrap",
  },
  motionPaused: {
    animationPlayState: "paused",
  },
  navigationPanel: {
    gap: "0.9rem",
    alignSelf: {
      default: "stretch",
      [breakpoints.compact]: "start",
    },
    display: "grid",
    gridTemplateRows: {
      default: "auto minmax(0, 1fr)",
      [breakpoints.compact]: "max-content max-content",
    },
    minHeight: {
      default: 0,
      [breakpoints.compact]: "max-content",
    },
  },
  navigationPanelArrived: {
    animationDelay: "85ms",
    animationDuration: "330ms",
    animationFillMode: "both",
    animationName: {
      default: panelArrival,
      [breakpoints.reducedMotion]: "none",
    },
    animationTimingFunction: motion.easeOut,
  },
  navigationHeader: {
    gap: "1rem",
    alignItems: "end",
    display: "flex",
    justifyContent: "space-between",
  },
  coordinateCounter: {
    color: colors.biolume,
    fontFamily: fonts.mono,
    fontSize: "0.52rem",
    letterSpacing: "0.12em",
    whiteSpace: "nowrap",
  },
  destinationList: {
    listStyle: "none",
    marginInline: "-0.35rem",
    paddingInline: {
      default: "1.2rem 1.5rem",
      [breakpoints.compact]: "0.8rem 1.25rem",
    },
    position: "relative",
    scrollbarWidth: "thin",
    maxHeight: {
      default: "100%",
      [breakpoints.compact]: null,
    },
    overflowX: "hidden",
    paddingBottom: "2.5rem",
    paddingTop: "0.1rem",
    "::before": {
      backgroundImage:
        "linear-gradient(to bottom, rgba(100, 240, 210, 0), rgba(100, 240, 210, 0.2) 10%, rgba(100, 240, 210, 0.13) 86%, rgba(100, 240, 210, 0))",
      content: '""',
      position: "absolute",
      bottom: "1.5rem",
      left: {
        default: "2.35rem",
        [breakpoints.compact]: "1.55rem",
      },
      top: "0.8rem",
      width: 1,
    },
  },
  destinationLink: {
    borderColor: {
      default: "rgba(159, 195, 207, 0.16)",
      ":hover": "rgba(100, 240, 210, 0.42)",
    },
    borderStyle: "solid",
    borderWidth: 1,
    gap: {
      default: "0.78rem",
      [breakpoints.compact]: "0.62rem",
    },
    paddingBlock: {
      default: "0.9rem",
      [breakpoints.compact]: "0.78rem",
    },
    paddingInline: {
      default: "0.9rem 0.8rem",
      [breakpoints.compact]: "0.75rem 0.65rem",
    },
    alignItems: "start",
    backgroundColor: {
      default: "rgba(5, 21, 29, 0.54)",
      ":hover": "rgba(7, 34, 40, 0.78)",
    },
    display: "grid",
    gridTemplateColumns: "auto minmax(0, 1fr) auto",
    position: "relative",
    scale: {
      default: "1",
      ":hover": "1.012",
    },
    transform: {
      default: "translateX(var(--echo-map-nav-shift)) rotate(var(--echo-map-nav-tilt))",
      ":focus-visible": "translateX(var(--echo-map-nav-shift)) rotate(0deg)",
    },
    transitionDuration: "260ms",
    transitionProperty: "background-color, border-color, opacity, scale, transform",
    transitionTimingFunction: motion.easeOut,
    borderBottomLeftRadius: 9,
    borderBottomRightRadius: 22,
    borderTopLeftRadius: 22,
    borderTopRightRadius: 9,
    marginTop: "var(--echo-map-nav-gap)",
    minHeight: 82,
  },
  destinationCurrent: {
    borderColor: "rgba(100, 240, 210, 0.6)",
    backgroundColor: "rgba(7, 45, 46, 0.72)",
    boxShadow: "0 0 26px rgba(100, 240, 210, 0.07), inset 0 0 24px rgba(100, 240, 210, 0.035)",
  },
  destinationPassed: {
    opacity: 0.68,
  },
  destinationPreviewed: {
    borderColor: "rgba(159, 195, 207, 0.46)",
    opacity: 1,
    scale: "1.018",
  },
  destinationMarker: {
    borderColor: "rgba(159, 195, 207, 0.68)",
    borderRadius: "50%",
    borderStyle: "solid",
    borderWidth: 1,
    backgroundColor: "rgba(1, 9, 16, 0.96)",
    boxShadow: "0 0 0 5px rgba(1, 9, 16, 0.78)",
    position: "relative",
    zIndex: 1,
    height: 11,
    marginTop: "0.24rem",
    width: 11,
  },
  markerCurrent: {
    borderColor: colors.biolume,
    backgroundColor: colors.biolume,
    boxShadow: "0 0 0 5px rgba(1, 9, 16, 0.78), 0 0 17px rgba(100, 240, 210, 0.82)",
  },
  markerPassed: {
    backgroundColor: colors.ice,
  },
  destinationCopy: {
    display: "grid",
    minWidth: 0,
  },
  destinationMeta: {
    color: colors.biolume,
    fontFamily: fonts.mono,
    fontSize: {
      default: "0.48rem",
      [breakpoints.compact]: "0.43rem",
    },
    letterSpacing: "0.11em",
    lineHeight: 1.4,
    textTransform: "uppercase",
  },
  destinationTitle: {
    color: colors.iceBright,
    fontSize: {
      default: "0.86rem",
      [breakpoints.compact]: "0.78rem",
    },
    fontWeight: 590,
    lineHeight: 1.28,
    marginTop: "0.24rem",
  },
  destinationSummary: {
    overflow: "hidden",
    WebkitBoxOrient: "vertical",
    WebkitLineClamp: 2,
    color: "rgba(201, 218, 225, 0.62)",
    display: "-webkit-box",
    fontSize: {
      default: "0.68rem",
      [breakpoints.compact]: "0.64rem",
    },
    lineHeight: 1.42,
    marginTop: "0.3rem",
  },
  destinationState: {
    color: "rgba(159, 195, 207, 0.64)",
    fontFamily: fonts.mono,
    fontSize: {
      default: "0.43rem",
      [breakpoints.compact]: "0.39rem",
    },
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    whiteSpace: "nowrap",
    paddingTop: "0.16rem",
  },
  visuallyHidden: {
    overflow: "hidden",
    clipPath: "inset(50%)",
    position: "absolute",
    whiteSpace: "nowrap",
    height: 1,
    width: 1,
  },
});
