import * as stylex from "@stylexjs/stylex";
import { breakpoints, colors, fonts, motion } from "@/styles/tokens.stylex";
import { echoMapMotion } from "./motion.stylex";

const radarSweep = stylex.keyframes({
  from: { transform: "rotate(-38deg)" },
  to: { transform: "rotate(322deg)" },
});

const searchPulse = stylex.keyframes({
  "0%": { opacity: 0.62, transform: "translate(-50%, -50%) scale(0.12)" },
  "70%, 100%": { opacity: 0, transform: "translate(-50%, -50%) scale(1)" },
});

const contactAnswer = stylex.keyframes({
  "0%, 100%": { opacity: 0.5, scale: "0.78" },
  "38%": { opacity: 1, scale: "1.3" },
  "64%": { opacity: 0.82, scale: "1" },
});

const lockBreathing = stylex.keyframes({
  "0%, 100%": { boxShadow: "0 0 0 0 rgba(100, 240, 210, 0.2)" },
  "50%": { boxShadow: "0 0 0 9px rgba(100, 240, 210, 0)" },
});

const statusBlink = stylex.keyframes({
  "0%, 42%, 100%": { opacity: 1 },
  "48%, 55%": { opacity: 0.36 },
});

export const styles = stylex.create({
  dialog: {
    inset: 0,
    margin: 0,
    padding: 0,
    borderWidth: 0,
    overflow: "hidden",
    backgroundColor: "rgba(0, 4, 9, 0)",
    color: colors.bodyText,
    transitionDuration: echoMapMotion.closeDuration,
    transitionProperty: "background-color, backdrop-filter",
    transitionTimingFunction: motion.easeOut,
    height: {
      default: "100vh",
      "@supports (height: 100dvh)": "100dvh",
    },
    maxHeight: "none",
    maxWidth: "none",
    width: "100vw",
    "::backdrop": {
      backgroundColor: "transparent",
    },
  },
  dialogExpanded: {
    backdropFilter: "blur(13px) saturate(0.72)",
    backgroundColor: "rgba(0, 4, 9, 0.76)",
  },
  stage: {
    padding: {
      default: "clamp(0.7rem, 2vw, 1.4rem)",
      [breakpoints.compact]: "0.45rem",
    },
    placeItems: "center",
    display: "grid",
    position: "relative",
    height: "100%",
    width: "100%",
  },
  backdropButton: {
    inset: 0,
    padding: 0,
    borderWidth: 0,
    backgroundColor: "transparent",
    cursor: "default",
    position: "absolute",
  },
  console: {
    borderColor: "rgba(159, 195, 207, 0.42)",
    borderRadius: 54,
    borderStyle: "solid",
    borderWidth: 1,
    overflow: "hidden",
    backgroundColor: "rgba(1, 9, 16, 0.975)",
    backgroundImage:
      "radial-gradient(circle at 13% 7%, rgba(100, 240, 210, 0.09), transparent 28%), radial-gradient(circle at 82% 92%, rgba(70, 121, 154, 0.11), transparent 34%), linear-gradient(rgba(100, 240, 210, 0.026) 1px, transparent 1px), linear-gradient(90deg, rgba(100, 240, 210, 0.026) 1px, transparent 1px)",
    backgroundSize: "auto, auto, 52px 52px, 52px 52px",
    boxShadow: "0 34px 110px rgba(0, 0, 0, 0.62), inset 0 1px 0 rgba(230, 241, 244, 0.08)",
    display: "grid",
    gridTemplateRows: "auto minmax(0, 1fr)",
    opacity: 0.24,
    pointerEvents: "auto",
    position: "relative",
    transform:
      "translate3d(var(--echo-map-translate-x), var(--echo-map-translate-y), 0) scale(var(--echo-map-scale-x), var(--echo-map-scale-y))",
    transformOrigin: "50% 50%",
    transitionDuration: echoMapMotion.openDuration,
    transitionProperty: "transform, opacity, border-radius, box-shadow",
    transitionTimingFunction: "cubic-bezier(0.16, 1, 0.3, 1)",
    willChange: "transform, opacity",
    zIndex: 1,
    height: "min(49rem, 100%)",
    maxWidth: 1180,
    width: "100%",
  },
  consoleExpanded: {
    borderRadius: {
      default: 30,
      [breakpoints.compact]: 22,
    },
    opacity: 1,
    transform: "translate3d(0, 0, 0) scale(1, 1)",
  },
  consoleClosing: {
    borderRadius: 54,
    pointerEvents: "none",
    transitionDuration: echoMapMotion.closeDuration,
    transitionTimingFunction: "cubic-bezier(0.55, 0, 0.84, 0.24)",
  },
  consoleHeader: {
    gap: "1rem",
    paddingBlock: {
      default: "1rem",
      [breakpoints.compact]: "0.72rem",
    },
    paddingInline: {
      default: "clamp(1.15rem, 2.4vw, 2rem)",
      [breakpoints.compact]: "0.85rem",
    },
    alignItems: "center",
    display: "flex",
    justifyContent: "space-between",
    borderBottomColor: "rgba(159, 195, 207, 0.18)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    minHeight: {
      default: 90,
      [breakpoints.compact]: 76,
    },
  },
  identity: {
    gap: {
      default: "0.9rem",
      [breakpoints.compact]: "0.65rem",
    },
    alignItems: "center",
    display: "flex",
    minWidth: 0,
  },
  titleGroup: {
    minWidth: 0,
  },
  vehicleMark: {
    overflow: "hidden",
    flexBasis: "auto",
    flexGrow: 0,
    flexShrink: 0,
    position: "relative",
    height: {
      default: 58,
      [breakpoints.compact]: 48,
    },
    width: {
      default: 44,
      [breakpoints.compact]: 36,
    },
  },
  eyebrow: {
    overflow: "hidden",
    color: colors.biolume,
    fontFamily: fonts.mono,
    fontSize: {
      default: "0.54rem",
      [breakpoints.compact]: "0.47rem",
    },
    letterSpacing: {
      default: "0.18em",
      [breakpoints.compact]: "0.1em",
    },
    textOverflow: "ellipsis",
    textTransform: "uppercase",
    whiteSpace: "nowrap",
  },
  heading: {
    color: colors.iceBright,
    fontSize: {
      default: "clamp(1.75rem, 3vw, 2.8rem)",
      [breakpoints.compact]: "1.45rem",
    },
    fontVariationSettings: '"wdth" 108',
    fontWeight: 680,
    letterSpacing: "0.025em",
    lineHeight: 0.96,
    textTransform: "uppercase",
    marginTop: "0.28rem",
  },
  closeButton: {
    borderColor: {
      default: "rgba(159, 195, 207, 0.34)",
      ":hover": "rgba(100, 240, 210, 0.78)",
    },
    borderRadius: 999,
    borderStyle: "solid",
    borderWidth: 1,
    padding: 0,
    backgroundColor: {
      default: "rgba(1, 9, 14, 0.54)",
      ":hover": "rgba(100, 240, 210, 0.09)",
    },
    color: {
      default: colors.ice,
      ":hover": colors.biolume,
    },
    cursor: "pointer",
    display: "grid",
    flexBasis: "auto",
    flexGrow: 0,
    flexShrink: 0,
    fontFamily: fonts.mono,
    fontSize: "1.45rem",
    fontWeight: 300,
    lineHeight: 1,
    placeItems: "center",
    scale: {
      default: "1",
      ":active": "0.94",
      ":hover": "1.04",
    },
    transitionDuration: "220ms",
    transitionProperty: "background-color, border-color, color, scale",
    transitionTimingFunction: motion.easeOut,
    height: 44,
    minHeight: 44,
    minWidth: 44,
    width: 44,
  },
  consoleBody: {
    padding: {
      default: "clamp(1rem, 2.4vw, 2rem)",
      [breakpoints.compact]: "0.8rem",
    },
    gap: {
      default: "clamp(1.3rem, 3vw, 2.8rem)",
      [breakpoints.compact]: "1rem",
    },
    overflow: {
      default: "hidden",
      [breakpoints.compact]: "auto",
    },
    display: "grid",
    gridTemplateColumns: {
      default: "minmax(18rem, 1.05fr) minmax(20rem, 0.95fr)",
      [breakpoints.mediumOnly]: "minmax(16rem, 0.92fr) minmax(18rem, 1.08fr)",
      [breakpoints.compact]: "1fr",
    },
    minHeight: 0,
  },
  radarPanel: {
    gap: "0.85rem",
    alignContent: "start",
    display: "grid",
    minHeight: 0,
  },
  panelHeader: {
    gap: "1rem",
    alignItems: "start",
    display: "flex",
    justifyContent: "space-between",
  },
  panelLabel: {
    color: colors.ice,
    fontFamily: fonts.mono,
    fontSize: "0.52rem",
    letterSpacing: "0.16em",
    lineHeight: 1.5,
    textTransform: "uppercase",
  },
  liveStatus: {
    gap: "0.42rem",
    alignItems: "center",
    color: "rgba(100, 240, 210, 0.76)",
    display: "inline-flex",
    fontFamily: fonts.mono,
    fontSize: "0.48rem",
    letterSpacing: "0.1em",
    textTransform: "uppercase",
  },
  liveDot: {
    borderRadius: "50%",
    animationDuration: "3.8s",
    animationIterationCount: "infinite",
    animationName: {
      default: statusBlink,
      [breakpoints.reducedMotion]: "none",
    },
    backgroundColor: colors.biolume,
    boxShadow: "0 0 8px rgba(100, 240, 210, 0.62)",
    height: 6,
    width: 6,
  },
  description: {
    color: "rgba(201, 218, 225, 0.67)",
    fontSize: {
      default: "0.79rem",
      [breakpoints.compact]: "0.73rem",
    },
    lineHeight: 1.55,
    maxWidth: "54ch",
  },
  radarField: {
    margin: 0,
    borderColor: "rgba(100, 240, 210, 0.25)",
    borderRadius: "50%",
    borderStyle: "solid",
    borderWidth: 1,
    overflow: "hidden",
    aspectRatio: "1",
    backgroundColor: "rgba(0, 15, 22, 0.64)",
    backgroundImage:
      "radial-gradient(circle, rgba(100, 240, 210, 0.025) 0 2%, transparent 2.2%), radial-gradient(circle, transparent 24.5%, rgba(100, 240, 210, 0.12) 24.8%, transparent 25.2%, transparent 49.5%, rgba(100, 240, 210, 0.1) 49.8%, transparent 50.2%, transparent 74.5%, rgba(100, 240, 210, 0.08) 74.8%, transparent 75.2%), radial-gradient(circle at center, rgba(9, 66, 72, 0.22), rgba(0, 8, 15, 0.08) 68%)",
    boxShadow: "inset 0 0 44px rgba(0, 0, 0, 0.62), 0 0 40px rgba(100, 240, 210, 0.055)",
    justifySelf: "center",
    position: "relative",
    width: {
      default: "min(100%, 28.5rem)",
      [breakpoints.compact]: "min(58vw, 13.5rem)",
    },
  },
  radarAxes: {
    inset: "8%",
    borderRadius: "50%",
    backgroundImage:
      "linear-gradient(transparent 49.7%, rgba(100, 240, 210, 0.11) 50%, transparent 50.3%), linear-gradient(90deg, transparent 49.7%, rgba(100, 240, 210, 0.11) 50%, transparent 50.3%)",
    position: "absolute",
  },
  radarSweep: {
    inset: "2.5%",
    borderRadius: "50%",
    backgroundImage:
      "conic-gradient(from -18deg, transparent 0deg, rgba(100, 240, 210, 0.02) 25deg, rgba(100, 240, 210, 0.34) 43deg, transparent 47deg)",
    opacity: 0,
    position: "absolute",
    transform: "rotate(-38deg)",
    transformOrigin: "50% 50%",
  },
  radarSweepActive: {
    animationDuration: "5.4s",
    animationIterationCount: "infinite",
    animationName: {
      default: radarSweep,
      [breakpoints.reducedMotion]: "none",
    },
    animationTimingFunction: "linear",
    opacity: 1,
  },
  searchPulse: {
    borderColor: "rgba(100, 240, 210, 0.48)",
    borderRadius: "50%",
    borderStyle: "solid",
    borderWidth: 1,
    opacity: 0,
    position: "absolute",
    transform: "translate(-50%, -50%) scale(0.12)",
    height: "94%",
    left: "50%",
    top: "50%",
    width: "94%",
  },
  searchPulseActive: {
    animationDuration: "3.1s",
    animationIterationCount: "infinite",
    animationName: {
      default: searchPulse,
      [breakpoints.reducedMotion]: "none",
    },
    animationTimingFunction: "cubic-bezier(0.16, 1, 0.3, 1)",
  },
  contact: {
    borderColor: "rgba(100, 240, 210, 0.72)",
    borderRadius: "50%",
    borderStyle: "solid",
    borderWidth: 1,
    backgroundColor: "rgba(100, 240, 210, 0.2)",
    boxShadow: "0 0 8px rgba(100, 240, 210, 0.38)",
    display: "block",
    opacity: 0.52,
    scale: "0.78",
    transitionDuration: "260ms",
    transitionProperty: "background-color, box-shadow, opacity, scale",
    transitionTimingFunction: motion.easeOut,
    height: {
      default: 10,
      [breakpoints.compact]: 8,
    },
    width: {
      default: 10,
      [breakpoints.compact]: 8,
    },
  },
  contactActive: {
    animationDuration: "1.25s",
    animationName: {
      default: contactAnswer,
      [breakpoints.reducedMotion]: "none",
    },
    animationTimingFunction: motion.easeOut,
    backgroundColor: colors.biolume,
    boxShadow: "0 0 5px rgba(230, 241, 244, 0.8), 0 0 20px rgba(100, 240, 210, 0.9)",
    opacity: 1,
    scale: "1.15",
  },
  contactLabel: {
    color: colors.biolume,
    fontFamily: fonts.mono,
    fontSize: "0.42rem",
    letterSpacing: "0.08em",
    opacity: 0,
    position: "absolute",
    textShadow: "0 0 10px rgba(100, 240, 210, 0.8)",
    textTransform: "uppercase",
    transform: "translate(-42%, 0.7rem)",
    transitionDuration: "260ms",
    transitionProperty: "opacity, transform",
    transitionTimingFunction: motion.easeOut,
    whiteSpace: "nowrap",
  },
  contactLabelActive: {
    opacity: {
      default: 0.92,
      [breakpoints.compact]: 0,
    },
    transform: "translate(-42%, 0.9rem)",
  },
  centerLock: {
    borderColor: "rgba(100, 240, 210, 0.46)",
    borderRadius: "50%",
    borderStyle: "solid",
    borderWidth: 1,
    placeItems: "center",
    backgroundColor: "rgba(1, 9, 16, 0.86)",
    display: "grid",
    position: "absolute",
    transform: "translate(-50%, -50%)",
    height: {
      default: 72,
      [breakpoints.compact]: 58,
    },
    left: "50%",
    top: "50%",
    width: {
      default: 72,
      [breakpoints.compact]: 58,
    },
  },
  centerLockActive: {
    animationDuration: "3.2s",
    animationIterationCount: "infinite",
    animationName: {
      default: lockBreathing,
      [breakpoints.reducedMotion]: "none",
    },
    animationTimingFunction: "ease-in-out",
  },
  centerDepth: {
    color: colors.iceBright,
    fontFamily: fonts.mono,
    fontSize: {
      default: "0.58rem",
      [breakpoints.compact]: "0.48rem",
    },
    letterSpacing: "0.08em",
    textAlign: "center",
    textShadow: "0 0 12px rgba(100, 240, 210, 0.45)",
    textTransform: "uppercase",
  },
  radarReadout: {
    borderColor: "rgba(159, 195, 207, 0.18)",
    borderRadius: 14,
    borderStyle: "solid",
    borderWidth: 1,
    gap: "0.75rem",
    paddingBlock: "0.72rem",
    paddingInline: "0.8rem",
    alignItems: "center",
    backgroundColor: "rgba(2, 15, 22, 0.72)",
    display: "grid",
    gridTemplateColumns: "auto minmax(0, 1fr) auto",
    minWidth: 0,
  },
  contactKind: {
    color: colors.biolume,
    fontFamily: fonts.mono,
    fontSize: "0.46rem",
    letterSpacing: "0.11em",
    textTransform: "uppercase",
  },
  contactName: {
    overflow: "hidden",
    color: colors.iceBright,
    fontSize: {
      default: "0.76rem",
      [breakpoints.compact]: "0.7rem",
    },
    fontWeight: 560,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  contactVector: {
    color: "rgba(159, 195, 207, 0.72)",
    fontFamily: fonts.mono,
    fontSize: "0.48rem",
    letterSpacing: "0.06em",
    textAlign: "right",
    whiteSpace: "nowrap",
  },
  motionPaused: {
    animationPlayState: "paused",
  },
  navigationPanel: {
    gap: "0.9rem",
    display: "grid",
    gridTemplateRows: "auto minmax(0, 1fr)",
    minHeight: 0,
  },
  navigationHeader: {
    gap: "1rem",
    alignItems: "end",
    display: "flex",
    justifyContent: "space-between",
  },
  coordinateCounter: {
    color: colors.biolume,
    fontFamily: fonts.mono,
    fontSize: "0.52rem",
    letterSpacing: "0.12em",
    whiteSpace: "nowrap",
  },
  destinationList: {
    listStyle: "none",
    marginInline: "-0.35rem",
    paddingInline: {
      default: "1.2rem 1.5rem",
      [breakpoints.compact]: "0.8rem 1.25rem",
    },
    position: "relative",
    scrollbarWidth: "thin",
    maxHeight: {
      default: "100%",
      [breakpoints.compact]: "min(42vh, 21rem)",
    },
    minHeight: 0,
    overflowX: "hidden",
    overflowY: "auto",
    paddingBottom: "2.5rem",
    paddingTop: "0.1rem",
    "::before": {
      backgroundImage:
        "linear-gradient(to bottom, rgba(100, 240, 210, 0), rgba(100, 240, 210, 0.2) 10%, rgba(100, 240, 210, 0.13) 86%, rgba(100, 240, 210, 0))",
      content: '""',
      position: "absolute",
      bottom: "1.5rem",
      left: {
        default: "2.35rem",
        [breakpoints.compact]: "1.55rem",
      },
      top: "0.8rem",
      width: 1,
    },
  },
  destinationLink: {
    borderColor: {
      default: "rgba(159, 195, 207, 0.16)",
      ":hover": "rgba(100, 240, 210, 0.42)",
    },
    borderStyle: "solid",
    borderWidth: 1,
    gap: {
      default: "0.78rem",
      [breakpoints.compact]: "0.62rem",
    },
    paddingBlock: {
      default: "0.9rem",
      [breakpoints.compact]: "0.78rem",
    },
    paddingInline: {
      default: "0.9rem 0.8rem",
      [breakpoints.compact]: "0.75rem 0.65rem",
    },
    alignItems: "start",
    backgroundColor: {
      default: "rgba(5, 21, 29, 0.54)",
      ":hover": "rgba(7, 34, 40, 0.78)",
    },
    display: "grid",
    gridTemplateColumns: "auto minmax(0, 1fr) auto",
    position: "relative",
    scale: {
      default: "1",
      ":hover": "1.012",
    },
    transform: {
      default: "translateX(var(--echo-map-nav-shift)) rotate(var(--echo-map-nav-tilt))",
      ":focus-visible": "translateX(var(--echo-map-nav-shift)) rotate(0deg)",
    },
    transitionDuration: "260ms",
    transitionProperty: "background-color, border-color, opacity, scale, transform",
    transitionTimingFunction: motion.easeOut,
    borderBottomLeftRadius: 9,
    borderBottomRightRadius: 22,
    borderTopLeftRadius: 22,
    borderTopRightRadius: 9,
    marginTop: "var(--echo-map-nav-gap)",
    minHeight: 82,
  },
  destinationCurrent: {
    borderColor: "rgba(100, 240, 210, 0.6)",
    backgroundColor: "rgba(7, 45, 46, 0.72)",
    boxShadow: "0 0 26px rgba(100, 240, 210, 0.07), inset 0 0 24px rgba(100, 240, 210, 0.035)",
  },
  destinationPassed: {
    opacity: 0.68,
  },
  destinationPreviewed: {
    borderColor: "rgba(159, 195, 207, 0.46)",
    opacity: 1,
    scale: "1.018",
  },
  destinationMarker: {
    borderColor: "rgba(159, 195, 207, 0.68)",
    borderRadius: "50%",
    borderStyle: "solid",
    borderWidth: 1,
    backgroundColor: "rgba(1, 9, 16, 0.96)",
    boxShadow: "0 0 0 5px rgba(1, 9, 16, 0.78)",
    position: "relative",
    zIndex: 1,
    height: 11,
    marginTop: "0.24rem",
    width: 11,
  },
  markerCurrent: {
    borderColor: colors.biolume,
    backgroundColor: colors.biolume,
    boxShadow: "0 0 0 5px rgba(1, 9, 16, 0.78), 0 0 17px rgba(100, 240, 210, 0.82)",
  },
  markerPassed: {
    backgroundColor: colors.ice,
  },
  destinationCopy: {
    display: "grid",
    minWidth: 0,
  },
  destinationMeta: {
    color: colors.biolume,
    fontFamily: fonts.mono,
    fontSize: {
      default: "0.48rem",
      [breakpoints.compact]: "0.43rem",
    },
    letterSpacing: "0.11em",
    lineHeight: 1.4,
    textTransform: "uppercase",
  },
  destinationTitle: {
    color: colors.iceBright,
    fontSize: {
      default: "0.86rem",
      [breakpoints.compact]: "0.78rem",
    },
    fontWeight: 590,
    lineHeight: 1.28,
    marginTop: "0.24rem",
  },
  destinationSummary: {
    overflow: "hidden",
    WebkitBoxOrient: "vertical",
    WebkitLineClamp: 2,
    color: "rgba(201, 218, 225, 0.62)",
    display: "-webkit-box",
    fontSize: {
      default: "0.68rem",
      [breakpoints.compact]: "0.64rem",
    },
    lineHeight: 1.42,
    marginTop: "0.3rem",
  },
  destinationState: {
    color: "rgba(159, 195, 207, 0.64)",
    fontFamily: fonts.mono,
    fontSize: {
      default: "0.43rem",
      [breakpoints.compact]: "0.39rem",
    },
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    whiteSpace: "nowrap",
    paddingTop: "0.16rem",
  },
  visuallyHidden: {
    overflow: "hidden",
    clipPath: "inset(50%)",
    position: "absolute",
    whiteSpace: "nowrap",
    height: 1,
    width: 1,
  },
});
